name: Renamer Tests
on: [push]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: set-up-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install-python-dependancies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: run-unit-tests
        run: make test
